from typing import TypedDict


class RepairAgentState(TypedDict):
    """
    Shared state passed between all LangGraph nodes.
    """

    # Original IoT alert received from the API
    alert: dict

    # Query generated from the IoT alert
    query: str

    # Text retrieved from the vector database
    retrieved_context: str

    # Prompt sent to the LLM
    prompt: str

    # Final repair plan generated by the LLM
    repair_plan: str

    # Inventory lookup results (used later)
    inventory: dict